name: Bug report
description: File a bug report
title: "[Bug]: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file this issue! Please make sure that you have search through both open and closed issues for your bug to avoid duplications.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug
      value: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: Provide details about your OS, app version, etc.
      value: |
        - OS: [e.g. Windows 11 Insider, Alpine Linux 3.16.2, MacOS] (Only for reporting issues in 'example')
        - Architecture: [e.g. 64-bits, 32-bits, ARM] (Only for reporting issues in 'example')
        - Programming language version: [e.g. Node.js 18.X, Python 3.11.X] (Only for reporting issues in 'example')
        - Date: [01/25/2023] - Preferably in `MM/DD/YYYY` format
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
